# Generated by Django 6.0.6 on 2026-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('engine', models.CharField(choices=[('arcface', 'arcface'), ('dlib', 'dlib')], help_text='Backend the embedding below was produced with.', max_length=20)),
                ('embedding', models.JSONField(help_text='L2-normalized embedding vector.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('det_score', models.FloatField(default=0.0)),
                ('num_source_photos', models.PositiveSmallIntegerField(default=1, help_text='1 = pure one-shot, >1 if enrolled with TTA/multi-photo averaging.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
